### ISSUE TITLE
Convert units

### ISSUE THREAD

**Issue by nkootstra** [nkootstra/unit-conversion#1]
- [ ] Be able to convert from one unit to another

**Comment by Soben** [comment]
I feel like this could be a fun challenge, and I'll try my hand on it. Don't hold me to it though :-D

**Comment by nkootstra** [comment]
Nice. I already got something I have to push. It looks something like this:

```php
$from = new MilliLiter(500);

$into = $from->to(Liter::class);

$this->assertInstanceOf(Liter::class, $into);
$this->assertEquals(0.5, $into->getQuantity());
```

**Comment by nkootstra** [comment]
I pushed it. Maybe you can optimize it?

**Comment by Soben** [comment]
Nice! I had something similar in mind but a little more intense.

I'll take a look at what you have and see what I can do to optimize.

**Comment by nkootstra** [comment]
Thanks :)
